const PageDta = [
  {
    id: 1,
    title: "iPhone 9",
    description: "An apple mobile which is nothing like apple",
    price: 549,
    discountPercentage: 12.96,
    rating: 4.69,
    stock: 94,
    brand: "website",
    category: "smartphones",
    thumbnail: "/portfolio/tem01.webp",
    logo: "/Clients_logo/Picture01.png",
    link: "https://ganacherybd.com/",
  },
  {
    id: 2,
    title: "iPhone X",
    description:
      "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
    price: 899,
    discountPercentage: 17.94,
    rating: 4.44,
    stock: 34,
    brand: "software",
    category: "smartphones",
    thumbnail: "/portfolio/tem02.webp",
    logo: "/Clients_logo/insignia.png",
    link: "https://insignia-resorts.com/",
  },
  {
    id: 3,
    title: "Samsung Universe 9",
    description:
      "Samsung's new variant which goes beyond Galaxy to the Universe",
    price: 1249,
    discountPercentage: 15.46,
    rating: 4.09,
    stock: 36,
    brand: "8888888",
    category: "smartphones",    
    thumbnail: "/portfolio/tem03.webp",
    logo: "/Clients_logo/Picture8.png",
    link: "",
  },
  {
    id: 4,
    title: "OPPOF19",
    description: "OPPO F19 is officially announced on April 2021.",
    price: 280,
    discountPercentage: 17.91,
    rating: 4.3,
    stock: 123,
    brand: "website",
    category: "smartphones",
    thumbnail: "/portfolio/tem05.webp",
    logo: "/Clients_logo/IFAD-Autos.png",
    link: "https://ifadautos.com",
  },
  {
    id: 5,
    title: "Huawei P30",
    description:
      "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
    price: 499,
    discountPercentage: 10.58,
    rating: 4.09,
    stock: 32,
    brand: "website",
    category: "smartphones",
    thumbnail: "/portfolio/tem04.webp",
    logo: "/Clients_logo/IFAD-Motors.png",
    link: "",
  },
  {
    id: 6,
    title: "MacBook Pro",
    description:
      "MacBook Pro 2021 with mini-LED display may launch between September, November",
    price: 1749,
    discountPercentage: 11.02,
    rating: 4.57,
    stock: 83,
    brand: "website",
    category: "laptops",
    thumbnail: "/portfolio/tem06.webp",
    logo: "/Clients_logo/IFAD-Multi-Products.png",
    link: "https://www.ifadmultiproducts.com",
  },
  {
    id: 7,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "ecommerce",
    category: "laptops",
    thumbnail: "/portfolio/IfadShop.webp",
    logo: "/Clients_logo/IFAD-ESHOP-Logo.png",
    link: "https://ifadeshop.com",
  },
  {
    id: 8,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "software",
    category: "laptops",
    thumbnail: "/portfolio/haefa.webp",
    logo: "/Clients_logo/haefa.png",
    link: "https://haefa.org/",
  },
  {
    id: 9,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "IT_Maintenance",
    category: "laptops",
    thumbnail: "/portfolio/Bcb.webp",
    logo: "/Clients_logo/bcb.png",
    link: "https://www.tigercricket.com.bd/",
  },
  {
    id: 10,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "website",
    category: "laptops",
    thumbnail: "/portfolio/tangonTravel.webp",
    logo: "/Clients_logo/tangontravels.png",
    link: "http://tangon.biz/",
  },
  {
    id: 11,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "website",
    category: "laptops",
    thumbnail: "/portfolio/muslinsahitto.webp",
    logo: "/Clients_logo/muslim.png",
    link: "http://muslimsahityasangsad.com/",
  },
  {
    id: 12,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "website",
    category: "laptops",
    thumbnail: "/portfolio/travelworld.webp",
    logo: "/Clients_logo/travelworld.png",
    link: "https://ttw.com.bd/",
  },
  {
    id: 13,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "website",
    category: "laptops",
    thumbnail: "/portfolio/thamesopticTemplate.webp",
    logo: "/Clients_logo/thamesoptic.png",
    link: "https://thamesoptic.com",
  },
  {
    id: 14,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "software",
    category: "laptops",
    thumbnail: "/portfolio/WaterDevelopmrentBoard.webp",
    logo: "/Clients_logo/Picture1.png",
    link: "https://www.bwdb.gov.bd",
  },
  {
    id: 15,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "website",
    category: "laptops",
    thumbnail: "/portfolio/KENC.webp",
    logo: "/Clients_logo/Picture13.png",
    link: "https://www.kencbd.com",
  },
  {
    id: 16,
    title: "Samsung Galaxy Book",
    description:
      "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
    price: 1499,
    discountPercentage: 4.15,
    rating: 4.25,
    stock: 50,
    brand: "IT_Maintenance",
    category: "laptops",
    thumbnail: "/portfolio/BangladeshTennisFederation.webp",
    logo: "/Clients_logo/tennis.png",
    link: "https://www.facebook.com/bangladeshtennisfederation/",
  },

];

export default PageDta;
